# This is a basic workflow to help you get started with Actions

name: build-root-wheel

# Controls when the workflow will run
on: 
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: true
  OS_APPLICATION_CREDENTIAL_ID: '7f5b64a265244623a3a933308569bdba'
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  OS_AUTH_TYPE: 'v3applicationcredential'
  OS_AUTH_URL: 'https://keystone.cern.ch/v3'
  OS_IDENTITY_API_VERSION: 3
  OS_INTERFACE: 'public'
  OS_REGION_NAME: 'cern'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on:
      - self-hosted
      - linux
      - x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: vepadulano/root
          ref: pip-install-root
          path: rootsrc

      - name: Run cibuildwheel build
        run: |
          . /home/githubci/root-pip-action/actions-runner/venv/bin/activate
          pushd rootsrc
          cibuildwheel --output-dir ../wheelhouse --only cp312-manylinux_x86_64
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-ROOT-wheel
          path: ./wheelhouse/*.whl
          if-no-files-found: error